# Generated by Django 6.0.6 on 2026-06-04 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='考试名称')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('duration_minutes', models.IntegerField(help_text='考生实际答题时长，不得大于考试窗口', verbose_name='考试时长（分钟）')),
                ('total_questions', models.IntegerField(default=100, verbose_name='总题数')),
                ('total_score', models.IntegerField(default=100, verbose_name='总分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(help_text='18位身份证号，登录凭证', max_length=18, unique=True, verbose_name='身份证号')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '考生',
                'verbose_name_plural': '考生',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id_card'], name='idx_candidates_id_card')],
            },
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '未开始'), ('in_progress', '进行中'), ('finished', '已交卷')], default='pending', max_length=16, verbose_name='状态')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总分')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始答题时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='交卷时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='exam.candidate', verbose_name='考生')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='exam.exam', verbose_name='考试')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_candidates', to='exam.candidate', verbose_name='考生')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_candidates', to='exam.exam', verbose_name='考试')),
                ('exam_paper', models.OneToOneField(blank=True, help_text='组卷后自动关联，可为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exam.exampaper', verbose_name='试卷')),
            ],
            options={
                'verbose_name': '考试考生',
                'verbose_name_plural': '考试考生',
                'ordering': ['exam', 'candidate'],
            },
        ),
        migrations.CreateModel(
            name='ExamPaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(verbose_name='排序序号')),
                ('shuffled_options', models.JSONField(verbose_name='打乱后的选项')),
                ('score', models.IntegerField(default=1, help_text='组卷时从 QuestionType.score 读取并快照', verbose_name='本题分值')),
                ('original_answer', models.CharField(help_text='组卷时快照的正确答案（P1-005）', max_length=512, verbose_name='快照正确答案')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.exampaper', verbose_name='所属试卷')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.question', verbose_name='原始题目')),
            ],
            options={
                'verbose_name': '试卷题目',
                'verbose_name_plural': '试卷题目',
                'ordering': ['exam_paper', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, max_length=512, null=True, verbose_name='考生答案')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='是否正确')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='作答时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exam_paper_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='exam.exampaperquestion', verbose_name='试卷题目')),
            ],
            options={
                'verbose_name': '作答记录',
                'verbose_name_plural': '作答记录',
            },
        ),
        migrations.CreateModel(
            name='QuestionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_count', models.IntegerField(help_text='从该章节该题型抽取的题目数', verbose_name='抽题数量')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.chapter', verbose_name='出题章节')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_rules', to='exam.exam', verbose_name='所属考试')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.questiontype', verbose_name='题型')),
            ],
            options={
                'verbose_name': '出题规则',
                'verbose_name_plural': '出题规则',
                'ordering': ['exam', 'chapter', 'question_type'],
            },
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['exam', 'candidate'], name='idx_papers_exam_candidate'),
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['status'], name='idx_papers_status'),
        ),
        migrations.AlterUniqueTogether(
            name='examcandidate',
            unique_together={('exam', 'candidate')},
        ),
        migrations.AddIndex(
            model_name='exampaperquestion',
            index=models.Index(fields=['exam_paper'], name='idx_epq_paper'),
        ),
        migrations.AlterUniqueTogether(
            name='questionrule',
            unique_together={('exam', 'chapter', 'question_type')},
        ),
    ]
