# Generated by Django 6.0.6 on 2026-06-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='passing_score',
            field=models.IntegerField(default=60, help_text='考生达到此分数视为及格，默认 60 分', verbose_name='及格分数线'),
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('paused', '已暂停'), ('cancelled', '已取消'), ('finished', '已结束')], default='draft', help_text='DRAFT=草稿 PUBLISHED=已发布 PAUSED=已暂停 CANCELLED=已取消 FINISHED=已结束', max_length=16, verbose_name='状态'),
        ),
    ]
