# Generated by Django 5.0.14 on 2026-06-04 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='题型名称')),
                ('code', models.CharField(help_text='编程用标识，如 single_choice, multi_choice, judgment', max_length=32, unique=True, verbose_name='题型代码')),
                ('score', models.IntegerField(default=1, help_text='该题型每道题的分值，组卷时使用', verbose_name='每题分值')),
            ],
            options={
                'verbose_name': '题型',
                'verbose_name_plural': '题型',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='章节名称')),
                ('sort_order', models.IntegerField(default=0, help_text='同级章节的排序序号，越小越靠前', verbose_name='排序')),
                ('level_depth', models.IntegerField(default=0, editable=False, help_text='自动计算：根节点=1，每深一层+1', verbose_name='层级深度')),
                ('parent', models.ForeignKey(blank=True, help_text='为空时表示根节点（章）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='questions.chapter', verbose_name='父章节')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'ordering': ['level_depth', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.TextField(help_text='题目内容，支持富文本', verbose_name='题干')),
                ('options', models.JSONField(default=list, help_text='JSON 数组格式，如 ["A. 选项A", "B. 选项B", ...]', verbose_name='选项列表')),
                ('answer', models.CharField(help_text='单选="A", 多选="A,B,C", 判断="正确"/"错误"', max_length=512, verbose_name='正确答案')),
                ('analysis', models.TextField(blank=True, help_text='可选，考试后展示给考生', null=True, verbose_name='答案解析')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('chapter', models.ForeignKey(help_text='PROTECT：有题目引用该章节时禁止删除', on_delete=django.db.models.deletion.PROTECT, to='questions.chapter', verbose_name='所属章节')),
                ('question_type', models.ForeignKey(help_text='PROTECT：有题目使用该题型时禁止删除', on_delete=django.db.models.deletion.PROTECT, to='questions.questiontype', verbose_name='题型')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['question_type', 'chapter'], name='idx_questions_type_chapter')],
            },
        ),
    ]
